apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  clusterIP: 10.96.2.8
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: airflow-redis
  type: ClusterIP

---

kind: Service
apiVersion: v1
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  clusterIP: 10.96.2.8
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    name: airflow-redis
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-redis
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-redis
  template:
    metadata:
      labels:
        name: airflow-redis
    spec:
      containers:
      - name: airflow-redis
        image: redis:5.0.5
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        resources:
          limits:
            cpu: 1
            memory: 2G
          requests:
            cpu: 0.2
            memory: 500Mi