apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  hostNetwork: true
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      automountServiceAccountToken: true
      serviceAccountName: airflow
      serviceAccount: airflow
      containers:
        - name: airflow-scheduler
          command: ["/bin/bash", "-c"]
          args: ["airflow scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-env
          image: moonlight165/wei_airflow:0.0.2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/airflow/logs
              mountPropagation: None
              name: data-analyze
              subPath: wei/logs
            - mountPath: /opt/airflow/dags
              mountPropagation: None
              name: data-analyze
              subPath: wei/dags
      volumes:
        - name: data-analyze
          persistentVolumeClaim:
            claimName: data-analyze
