kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: airflow-runner


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-cluster-role-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-runner-role